---
title: Institutions, Institutional Change and Economic Performance

author:
  - name: Carlos Enrique Lezama Jacinto
address:
  - address: Instituto Tecnológico Autónomo de México

corresponding_author:
  text: "One-pager written for the research seminar on institutional economics. E-mail: [clezamaj@itam.mx](mailto:clezamaj@itam.mx)."

pnas_type: pnasmathematics

bibliography: pnas-sample.bib
csl: pnas.csl

lineno: false

output: rticles::pnas_article
---

# Research Question / Tested Hypothesis / Main Argument {-}

This part analyzes the nature of the institutions and how they affect the performance of economies (or societies). Furthermore, it develops a theory of institutional change to explain how the past influences the present and the future through changes in institutions set at a time. The main objective is to understand the different behaviors of economies over time. The author affirms that institutions reduce uncertainty by providing structure to people's lives, guiding their interactions.

# Model / Assumptions {-}

The model focuses on how individuals make decisions (microeconomics approach). The author does not rely on traditional behavior assumptions and searches for initial motivations on economic agents' decisions. Therefore, our "initial" opportunity set plays a more relevant role than scarcity. If economies realize the gains from trade by creating relatively efficient institutions, it is because under certain circumstances the private objectives of those with the bargaining strength to alter institutions produce institutional solutions that turn out to be or evolve into socially efficient ones.

# Methodology {-}

It focuses on Game Theory concepts such as *cooperation* analyzing transaction costs, restrictions, social roles, and duties.

# Data {-}

N.A.

# Data Inventory {-}

N.A.

<!-- Leave these lines as they are at the end of your .Rmd file to ensure placement of methods & acknowledgements sections before the references-->
\showmatmethods
\showacknow
\pnasbreak
